import { BadRequestException, ValidationPipe } from '@nestjs/common';
import { RequestVerificationDto } from './dto/page-verification.dto';

describe('PageVerificationController request validation', () => {
  const pipe = new ValidationPipe({ whitelist: true, transform: true });
  const metadata = { type: 'body' as const, metatype: RequestVerificationDto };
  const pageId = '018f4b21-6c75-7a6a-8d5b-2c3d4e5f6a7b';
  const verifierId = '018f4b21-6c76-7a6a-8d5b-2c3d4e5f6a7b';

  it('accepts UUIDv7 verifier IDs generated by the database', async () => {
    await expect(
      pipe.transform({ pageId, verifierIds: [verifierId] }, metadata),
    ).resolves.toMatchObject({ pageId, verifierIds: [verifierId] });
  });

  it('rejects malformed verifier IDs before the request reaches the service', async () => {
    await expect(
      pipe.transform({ pageId, verifierIds: ['not-a-uuid'] }, metadata),
    ).rejects.toBeInstanceOf(BadRequestException);
  });
});
